CC = gcc

compile : main.c hybridSort.c estimateCutoff.c insertionSort.c quickSort.c testRun.c
	$(CC) main.c hybridSort.c estimateCutoff.c insertionSort.c quickSort.c testRun.c -o exe

test : test.c hybridSort.c estimateCutoff.c insertionSort.c quickSort.c testRun.c
	$(CC) test.c hybridSort.c estimateCutoff.c insertionSort.c quickSort.c testRun.c